name: SyncPSRuleSchema

on:
  push:
  schedule:
    - cron: '0 0 1 * *' # 00:00 on first day of each month
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: 'Checkout PSRule'
        uses: actions/checkout@v2.4.0
        with:
          repository: microsoft/PSRule
          path: PSRule

      - name: Configure
        run: |
          git config user.name github-actions
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Copy Schemas
        run: |
          $schemaDirectory = [System.IO.Path]::Combine($env:GITHUB_WORKSPACE, 'PSRule', 'schemas')
          Copy-Item -Path $schemaDirectory -Destination schemas -Recurse -Force
          git status